# PRODUCTION SCOPE
database:
  url: "jdbc:h2:~/r2db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
  username: "sa"
  password: ""
  schema: "main"

server:
  port: 8080
  host: 0.0.0.0
#  experimental:
#    http2:
#      enable: true
#      max-content-length: 16384